export const ACTION_GET_FACULTIES_STARTED = "GET_FACULTIES_STARTED";
export const ACTION_GET_FACULTIES_SUCCESS = "GET_FACULTIES_SUCCESS";
export const ACTION_GET_FACULTIES_FAILED = "GET_FACULTIES_FAILED";

export const ACTION_GET_TEACHERS_FOR_FACULTIES_STARTED = "GET_TEACHERS_FOR_FACULTIES_STARTED";
export const ACTION_GET_TEACHERS_FOR_FACULTIES_SUCCESS = "GET_TEACHERS_FOR_FACULTIES_SUCCESS";
export const ACTION_GET_TEACHERS_FOR_FACULTIES_FAILED = "GET_TEACHERS_FOR_FACULTIES_FAILED";

export const ACTION_GET_SUBJECTS_FOR_FACULTIES_STARTED = "GET_SUBJECTS_FOR_FACULTIES_STARTED";
export const ACTION_GET_SUBJECTS_FOR_FACULTIES_SUCCESS = "GET_SUBJECTS_FOR_FACULTIES_SUCCESS";
export const ACTION_GET_SUBJECTS_FOR_FACULTIES_FAILED = "GET_SUBJECTS_FOR_FACULTIES_FAILED";