export const ACTION_GET_FACULTIES_STARTED = "GET_FACULTIES_STARTED";
export const ACTION_GET_FACULTIES_SUCCESS = "GET_FACULTIES_SUCCESS";
export const ACTION_GET_FACULTIES_FAILED = "GET_FACULTIES_FAILED";